{{- if .Values.sensorService.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sensor-service-pdb
spec:
  minAvailable: {{ .Values.sensorService.pdb.minAvailable }}
  selector:
    matchLabels:
      app: sensor-service
{{- end }}
